### ISSUE TITLE
Tables Not Centering

### ISSUE THREAD

**Issue by ColtsFan18** [StarCitizenTools/mediawiki-skins-Citizen#352]
Content in tables is not centering with class="wikitable" style="margin:auto; text-align:center; font-size: 8pt;". It works on other skins. How do I fix this?

**Comment by alistair3149** [comment]
Thanks for reporting! It is a bug and should be fixed in bf8d927, would you mind to verify it?

**Comment by ColtsFan18** [comment]
Nope, it's still not working. Also, on mobile, I get this error where I can't expand sections.![image](https://user-images.githubusercontent.com/63676869/116451381-3f9b8800-a811-11eb-85f1-303d5cdf949a.jpeg)

**Comment by alistair3149** [comment]
Do you have a live demo of the site?
As for mobile, what browser and OS are you using?

**Comment by ColtsFan18** [comment]
http://coltsorg.com/wiki/Main_Page
iOS 14.5 using Firefox

**Comment by alistair3149** [comment]
Text are centered in the table on the Survivor: Sahara page.
As for the iOS issue I will get back to you if I find anything.

**Comment by ColtsFan18** [comment]
It doesn't seem to be centered on my end. 
![image](https://user-images.githubusercontent.com/63676869/116454863-44fad180-a815-11eb-846e-e8314251281b.png)

**Comment by alistair3149** [comment]
Hmm the issue seems to be the padding, you can put this in MediaWiki:Citizen.css in the meantime, I will look into a better way to implement the wikitable.
```css
table.wikitable tr th,
table.wikitable tr td {
	padding: 10px;
}
```

**Comment by ColtsFan18** [comment]
It works, thank you! Should I start another issue for the iOS issue?

**Comment by ColtsFan18** [comment]
Never mind, it's working on mobile now. Thanks for the help!
