### ISSUE TITLE
Pages not loading on Safari on Mac from the search bar

### ISSUE THREAD

**Issue by avtron** [StarCitizenTools/mediawiki-skins-Citizen#404]
## Describe the Bug
When I try to open a page from the search bar, it just slides away and doesn't open the page. It works on Chrome on Mac

1. Open Safari to a Citizen wiki
2. Click on the search bar
3. Attempt to search and open something

## Expected Behaviour
I expected it to open the page but it didn't.

## System
Client: Safari on macOS 11

Host: Just what the main SC tools wiki uses

**Comment by alistair3149** [comment]
Thanks for the report! Looking into it

**Comment by alistair3149** [comment]
It seems that Safari hide the search suggestion before the user can click onto the link:
https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/df7abc4010ee87356508b777bdd47a7c5cf3915a/resources/skins.citizen.search/typeahead.js#L275-L286

I don't have any Safari devices and I don't know how to solve it to be honest. Anyone got any ideas?

**Comment by alistair3149** [comment]
It might be fixed in one of the recent updates. Would you mind to check if it is an issue for you?
Also pinging @octfx he is a participant of the duplicated task

**Comment by alistair3149** [comment]
I don't have a wiki instance that can be tested with Safari. Would anyone be able to test if the latest patch work?

**Comment by octfx** [comment]
Haven't tested before, but everything works in beta.3  on iOS 16

**Comment by alistair3149** [comment]
Fixed in 2.0

**Comment by u32i64** [comment]
This is still reproducible on macOS with https://starcitizen.tools, or on e.g. https://signal.miraheze.org, while on iOS it works properly.

Selecting a search result/suggestion using the keyboard works, but it doesn't work using the mouse: the search suggestions disappear immediately, and nothing happens.

Interestingly, if I:
- Set a breakpoint on the `blur` event on `#searchInput` at https://signal.miraheze.org (https://starcitizen.tools doesn't seem to have a blur event there, though the issue is also reproducible);
- Click on a search result;
- Simply continue script execution by pressing the button in the debugger,

then the search result *is* correctly opened. This leads me to believe https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/9d8a631f44aac6ef97d4e2f51820c533352b5a93 could be the correct direction for the fix, but perhaps the delay needs to be larger?

---

**macOS:**
14.0 Beta (23A5312d) (but was reproducible on 13 too)
Safari 17.0 (19616.1.26.11.3)
Mac mini (M1, 2020)

**iOS:**
iOS 17.0 (21A5312c)
iPhone XR

**https://starcitizen.tools/Special:Version:**
MediaWiki 1.39.4
Citizen 2.7.5

**https://signal.miraheze.org/wiki/Special:Version:**
MediaWiki 1.39.4 (`cd34654`) 18:50, August 18, 2023
Citizen 2.7.5 (https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/ef5e081dc3d447f3f1db95816bde192b782a84b8) 01:18, July 18, 2023
